FROM harbor.k8s.temple.edu/library/ruby:2.7-alpine
# FROM harbor.k8s.temple.edu/library/ruby@sha256:26bc67d442972808126abb9b986af02b958891776c3261a2323f2ed9da32b8ca

WORKDIR /app

COPY . .

USER root

ARG RAILS_MASTER_KEY
ARG BUNDLE_PATH
ARG SPOTLIGHT_DB_USER
ARG SPOTLIGHT_DB_PASSWORD

RUN apk add -U --no-cache \
      bash=5.1.8-r0 \
      libxslt=1.1.34-r1 \
      tzdata=2021e-r0 \
      shared-mime-info=2.1-r0 \
      imagemagick=7.1.0.16-r0 \
      mariadb-connector-c=3.1.13-r2 \
      sudo=1.9.8_p2-r1 && \
    apk add -U --no-cache --virtual build-dependencies \
      git=2.34.1-r0 \
      build-base=0.5-r2 \
      libxslt-dev=1.1.34-r1 \
      mariadb-dev=10.6.4-r2 \
      mariadb-client=10.6.4-r2 \
      python3=3.9.7-r4 \
      nodejs=16.13.1-r0 \
      yarn=1.22.17-r0 && \
    python3 -m ensurepip && \
    gem install bundler:2.2.18 && \
    gem install rails:6.0.3 && \
    cp /app/my.cnf /.my.cnf && chmod 600 /.my.cnf && chown nobody:nobody /.my.cnf && \
    sed -i -r "s/DB_USER/${SPOTLIGHT_DB_USER}/g" /.my.cnf && sed -i -r "s/DB_PASSWORD/$SPOTLIGHT_DB_PASSWORD/g" /.my.cnf && \
    cp /app/dbdumptos3 /usr/local/bin/dbdumptos3 && chmod a+rx /usr/local/bin/dbdumptos3 && chown root:root /usr/local/bin/dbdumptos3 && \
    pip3 install awscli==1.22.19 && \
    mkdir -p /.aws && chmod 700 /.aws && chown nobody:nobody /.aws && \
    cp /app/files/aws_credentials /.aws/aws_credentials && chmod 600 /.aws/aws_credentials && chown nobody:nobody /.aws/aws_credentials && \
    cp /app/files/aws_config /.aws/aws_config && chmod 600 /.aws/aws_config && chown nobody:nobody /.aws/aws_config && \
    chmod +x .docker/app/entrypoint-dev.sh

ENTRYPOINT [".docker/app/entrypoint-dev.sh"]
EXPOSE 3000

CMD ["sleep", "infinity"]
