FROM harbor.k8s.temple.edu/library/ruby:2.7-alpine

WORKDIR /app

COPY . .

USER root

ARG RAILS_MASTER_KEY

RUN apk add -U --no-cache \
      bash=5.1.4-r0 \
      libxslt=1.1.34-r1 \
      tzdata=2021a-r0 \
      shared-mime-info=2.1-r0 \
      mariadb-connector-c=3.1.13-r0 && \
    apk add -U --no-cache --virtual build-dependencies \
      git=2.32.0-r0 \
      build-base=0.5-r2 \
      libxslt-dev=1.1.34-r1 \
      mariadb-dev=10.5.12-r0 \
      nodejs=14.17.6-r0 \
      yarn=1.22.10-r0 && \
    gem install bundler:2.2.17 && \
    gem install rails:6.0.3 && \
    chmod +x .docker/app/entrypoint-dev.sh

ENTRYPOINT [".docker/app/entrypoint-dev.sh"]
EXPOSE 3000

CMD ["sleep", "infinity"]
