# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV["SPOTLIGHT_DB_HOST"] || "127.0.0.1" %>
  database: <%= ENV["SPOTLIGHT_DB_NAME"] || "spotlight"  %>
  username: <%= ENV["SPOTLIGHT_DB_USER"] || "root" %>
  password: <%= ENV["SPOTLIGHT_DB_PASSWORD"] || "" %>
  port: 3306
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false

development:
  <<: *default
  database: spotlight

test:
  <<: *default
  database: <%= ENV["SPOTLIGHT_DB_NAME"] || "spotlight-test" %>

production:
  <<: *default
  host: <%= ENV["SPOTLIGHT_DB_HOST"] || "localhost" %>
  database: <%= ENV["SPOTLIGHT_DB_NAME"] %>
  username: <%= ENV["SPOTLIGHT_DB_USER"] %>
  password: <%= ENV["SPOTLIGHT_DB_PASSWORD"] %>
  pool: 5
  timeout: 5000
